FROM maven:3.6.2-jdk-11-slim AS build
COPY ./ /app
WORKDIR /app
RUN mvn clean package -U

FROM openjdk:11.0.4-jre-slim
RUN mkdir /app
WORKDIR /app
COPY --from=build ./app/target/comments-1.0.0-SNAPSHOT.jar /app
EXPOSE 8084
CMD ["java", "-jar", "comments-1.0.0-SNAPSHOT.jar"]
